---
title: "課堂練習模板"
author: "allen"
date: "2020-10-28"
output: output_format
params:
  id: "410973110"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
 names(listExample)
```
```{r}
listExample$student
listExample$學期

```
```{r}
listExample[["student"]]
listExample$student

listExample[["學期"]]  # 小心不是反頓點喔。
listExample$學期
```
```{r}
str(listExample, max.level = 1)

listExample[c(1, 2)]
```
```{r}
numVector <- c(2, 3, 6, -1, 4, 2, 6)
select1 <- numVector[c(1, 4)]
select1
select2 <- select1[[1]]
select2
```
```{r}
majors <- c("經濟學系", "經濟學系", "社會學系", "社工系", "經濟學系")
namesStudent <- c("小英", "小美", "大雄", "阿華", "阿尼")
genderStudent <- c("F", "F", "M", "F", "M")

```
```{r}
pickEcon<- c(T,T,F,F,F)
namesStudent[pickEcon]
genderStudent[pickEcon]

```
```{r}
which(pickEcon)
```
```{r}
namesStudent[pickEcon][[2]]
```
```{r}
today <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))
tomorrow <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))

weather <- list(today, tomorrow)

str(weather)

```
```{r}
weather[1]
```





